# Generated by Django 2.1.1 on 2018-09-04 23:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeProfile',
            new_name='NodeProfiles',
        ),
    ]
