# Generated by Django 2.1.1 on 2018-09-05 00:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('nodes', '0002_auto_20180904_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeProfiles',
            new_name='Nodes',
        ),
    ]
