# Generated by Django 2.1.1 on 2018-09-05 00:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('nodes', '0003_auto_20180905_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
    ]
